data:
  inner_splitter: 3
  outer_split_idx: 4
  outer_splitter: 1234
  split_seed: 1234
  split_strategy: random_rule_split
model:
  featurizer_mode: PROD_DIFF
  mp_d_h: 293
  mp_depth: 4
  pred_head_d_hs:
  - 138
  - 167
  - 196
  pred_head_name: ffn
training:
  batch_size: 113
  final_lr: 0.001
  init_lr: 0.0001
  max_epochs: 5
  max_lr: 0.0001
  pw_scl: 0.2727668128480795
  warmup_epochs: 2
