data:
  inner_splitter: 3
  outer_split_idx: 1
  outer_splitter: 1234
  split_seed: 1234
  split_strategy: random_rule_split
model:
  ckpt: 823268239766567171/952b1c9f489e4982b9c224d46887b4eb/artifacts/epoch=5-step=672/epoch=5-step=672.ckpt
  featurizer_mode: PROD_DIFF
  mp_d_h: 247
  mp_depth: 4
  pred_head_d_hs:
  - 156
  - 191
  - 117
  pred_head_name: ffn
training:
  batch_size: 109
  final_lr: 0.001
  init_lr: 0.0001
  max_epochs: 6
  max_lr: 0.0001
  pw_scl: 0.13466689503759408
  warmup_epochs: 2
